SET sql_mode = 'STRICT_ALL_TABLES';
CREATE TABLE USERS(
    id INT AUTO_INCREMENT PRIMARY KEY,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone_no VARCHAR(16) NOT NULL UNIQUE,
    address VARCHAR(128)
);