version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: haluk1234
      MYSQL_DATABASE: cs458-db
      MYSQL_USER: haluk
      MYSQL_PASSWORD: haluk123

    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql